openapi: '3.0.0'
info:
  title: API Title
  version: '1.0'
servers:
  - url:  http://localhost:3001/api


 
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header   

 
paths:
  
  /api/auth/login:
    post:
      tags:
        - user
      summary: 유저 로그인
      requestBody:
        required: true
        description: 료그인 요청을 보냅니다.
        content:
          application/json:
            schema:
              $ref:  "#/components/schemas/SignUp"
      responses:
        '201':
          description: Created
  /api/users:
    post:
      tags:
        - user
      summary: 유저 회원가입
      requestBody:
        required: true
        description: 회원가입 요청을 보냅니다.
        content:
          application/json:
            schema:
              $ref:  "#/components/schemas/SignUp"
      responses:
        '201':
          description: Created
          
components:
  schemas:
    Login:
      type: object
      properties:
        email:
          type: string 
          example: "shlifedev@gmail.com"
        password:
          type: string 
          example: "tjdgo123"
    SignUp:
      type: object
      properties:
        email:
          type: string 
          example: "shlifedev@gmail.com"
        password:
          type: string 
          example: "tjdgo123"

            